version: "3.9"

services:
    n-tier-api:
        container_name: n-tier-api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - n-tier-postgres

    n-tier-postgres:
        container_name: n-tier-postgres
        image: "postgres:15"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: "dev_password"
            POSTGRES_USER: "postgres"
            POSTGRES_DB: "n-tier-db"
        volumes:
            - postgres_dev_data:/var/lib/postgresql/data